# Jenkins master, running on default http 80 port
jenkins:
  image: jenkins
  ports:
    - "8000:8080"
    - "50000:50000"
  environment:
    - JENKINS_HOME=/Users/nicolas/java/src/github.com/ndeloof/cddemo-demos/jenkins-home
  volumes:
    # JENKINS_HOME, from host with pre-defined demo jobs
    - ./jenkins-home:/Users/nicolas/java/src/github.com/ndeloof/cddemo-demos/jenkins-home
    # Required host stuff so jenkins can run `docker` command to start containers
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /tmp:/tmp
  user: jenkins:staff # 'staff' group, required to access docker.sock  

# Jetty web server to run tests, staging and production
webserver:
  image: jetty:9
  ports:
    - "8080:8080"
  volumes:
    - ./webapps:/var/lib/jetty/webapps


